insert into tbl_car (maker, model, year_made) values ('Mazda', 'RX-8', 2009);
insert into tbl_car (maker, model, year_made) values ('Chevrolet', 'Astro', 2003);
insert into tbl_car (maker, model, year_made) values ('Infiniti', 'I', 1997);
insert into tbl_car (maker, model, year_made) values ('Ford', 'Expedition', 2002);
insert into tbl_car (maker, model, year_made) values ('Ford', 'E250', 2005);
insert into tbl_car (maker, model, year_made) values ('Buick', 'Regal', 1993);
insert into tbl_car (maker, model, year_made) values ('Toyota', 'Tacoma', 2009);
insert into tbl_car (maker, model, year_made) values ('Cadillac', 'Catera', 1998);
insert into tbl_car (maker, model, year_made) values ('GMC', 'Sierra 2500', 2006);
insert into tbl_car (maker, model, year_made) values ('Hyundai', 'Tucson', 2009);
insert into tbl_car (maker, model, year_made) values ('Dodge', 'Ram', 2011);
insert into tbl_car (maker, model, year_made) values ('Mitsubishi', 'Galant', 2010);
insert into tbl_car (maker, model, year_made) values ('Chevrolet', '1500', 1998);
insert into tbl_car (maker, model, year_made) values ('Saturn', 'Aura', 2008);
insert into tbl_car (maker, model, year_made) values ('BMW', 'Z3', 1999);
insert into tbl_car (maker, model, year_made) values ('Hummer', 'H2', 2005);
insert into tbl_car (maker, model, year_made) values ('Mitsubishi', 'Pajero', 1996);
insert into tbl_car (maker, model, year_made) values ('Mazda', '929', 1988);
insert into tbl_car (maker, model, year_made) values ('Aston Martin', 'DB9', 2006);
insert into tbl_car (maker, model, year_made) values ('Mitsubishi', 'Mirage', 1998);